name: Trigger Build Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
    uses: ./.github/workflows/Build.yml
    with:
      java-version: '11'
      distribution: 'temurin'
