name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Print "Hello, World!"
      - name: Hello World
        run: echo "Hello, World!"

  call-build-workflow:
    uses: ./.github/workflows/Build.yml
    with:
      java-version: '11'
      distribution: 'temurin'
